version: "3"
services:
  www:
    depends_on: 
    - mysql
    image: php:8.3.21-apache
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./www:/var/www/html

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  phpmyadmin:
    depends_on: 
    - mysql
    image: phpmyadmin:latest
    ports:
    - 81:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306 



