version: "3"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - docker-demo
  www:
    depends_on:
      - db
    image: php:8.3.2-apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www/html
    networks:
      - docker-demo
    command: "/bin/sh -c 'docker-php-ext-install mysqli && apache2-foreground'"
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    ports:
      - 81:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - docker-demo
networks:
  docker-demo:
    driver: bridge
